describe('modal Пошук: Контрагенти', () => {
    before(() => {
        cy.visit('/order/create?usa=1')
        cy.get('#form > div > div:nth-child(1) > div > div.row > div:nth-child(4) > div > a').click()

    })
    after(() => {
        cy.get('#modal-default > div > div > div.modal-header > button > span').first().click()
        cy.get('#modal-default').should('not.be.visible')
    })
    it('modal is opened', () => {
        cy.get('#modal-default').should('be.visible')
        cy.get('#modal-default > div > div > div.modal-header > h4 ')
            .contains('Пошук: Контрагенти')
            .should('be.visible')
    })
    it('should be declared 6 headers', () => {
        cy.get('#kontragents > thead > tr > th').should('be.visible').should('have.length', 6)

    })
    it('1 header should have text "ПІБ/Назва" and input', () => {
        cy.get('#kontragents > thead > tr > th:nth-child(1)')
            .contains('ПІБ/Назва')
            .should('be.visible')
        cy.get('#kontragents > thead > tr > th:nth-child(1) > input')
            .should('be.visible')
    })

    it('2 header should have text "Номер телефону" and input', () => {
        cy.get('#kontragents > thead > tr > th:nth-child(2)')
            .contains('Номер телефону')
            .should('be.visible')
        cy.get('#kontragents > thead > tr > th:nth-child(2) > input')
            .should('be.visible')
    })
    it('3 header should have text "Серія та номер паспорта" and input', () => {
        cy.get('#kontragents > thead > tr > th:nth-child(3)')
            .contains('Серія та номер паспорта:')
            .should('be.visible')
        cy.get('#kontragents > thead > tr > th:nth-child(3) > input')
            .should('be.visible')
    })
    it('4 header should have text "Код" and input', () => {
        cy.get('#kontragents > thead > tr > th:nth-child(4)')
            .contains('Код')
            .should('be.visible')
        cy.get('#kontragents > thead > tr > th:nth-child(4) > input')
            .should('be.visible')
    })
    it('5 header should have text "ІПН/ЄГРПОУ" and input', () => {
        cy.get('#kontragents > thead > tr > th:nth-child(5)')
            .contains('ІПН/ЄГРПОУ')
            .should('be.visible')
        cy.get('#kontragents > thead > tr > th:nth-child(5) > input')
            .should('be.visible')
    })
    it('6 header should have text "Дії" and a', () => {
        cy.get('#kontragents > thead > tr > th:nth-child(6)')
            .contains('Дії')
            .should('be.visible')
        cy.get('#kontragents > thead > tr > th:nth-child(6) > a')
            .should('be.visible')
    })
    it('should be declared 10 lines', () => {
        cy.get('#kontragents > tbody > tr').should('be.visible').should('have.length', 10)
    })
    it('1 lines should have text "Власов Михайло Олександрович"', () => {
        cy.get('#kontragents > tbody > tr:nth-child(1)')
            .contains('Власов Михайло Олександрович')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(1) > td:nth-child(2)')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(1) > td:nth-child(3)')
            .contains('СВ 101066')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(1) > td:nth-child(4)')
            .contains('000501649')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(1) > td:nth-child(5)')
            .contains('3047717993')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(1) > td:nth-child(6)')
            .should('be.visible')
    })
    it('2 lines should have text "Яценко Микита Віталійович"', () => {
        cy.get('#kontragents > tbody > tr:nth-child(2)')
            .contains('Яценко Микита Віталійович')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(2) > td:nth-child(2)')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(2) > td:nth-child(3)')
            .contains('002367993')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(2) > td:nth-child(4)')
            .contains('334347446')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(2) > td:nth-child(5)')
            .contains('3179904437')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(2) > td:nth-child(6)')
            .should('be.visible')
    })
    it('3 lines should have text "ТОВ "СПЕЦКОМСЕРВІС""', () => {
        cy.get('#kontragents > tbody > tr:nth-child(3)')
            .contains('ТОВ "СПЕЦКОМСЕРВІС"')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(3) > td:nth-child(2)')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(3) > td:nth-child(3)')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(3) > td:nth-child(4)')
            .contains('334661562')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(3) > td:nth-child(5)')
            .contains('32532336')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(3) > td:nth-child(6)')
            .should('be.visible')
    })
    it('4 lines should have text "Буряк Олександр Григорович"', () => {
        cy.get('#kontragents > tbody > tr:nth-child(4)')
            .contains('Буряк Олександр Григорович')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(4) > td:nth-child(2)')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(4) > td:nth-child(3)')
            .contains('001273761')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(4) > td:nth-child(4)')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(4) > td:nth-child(5)')
            .contains('2729510192')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(4) > td:nth-child(6)')
            .should('be.visible')
    })
    it('5 lines should have text "Кучинська Любов Миколаївна"', () => {
        cy.get('#kontragents > tbody > tr:nth-child(5)')
            .contains('Кучинська Любов Миколаївна')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(5) > td:nth-child(2)')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(5) > td:nth-child(3)')
            .contains('СВ 989328')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(5) > td:nth-child(4)')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(5) > td:nth-child(5)')
            .contains('2939209948')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(5) > td:nth-child(6)')
            .should('be.visible')
    })
    it('6 lines should have text "Ширін Артур Ігорович"', () => {
        cy.get('#kontragents > tbody > tr:nth-child(6)')
            .contains('Ширін Артур Ігорович')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(6) > td:nth-child(2)')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(6) > td:nth-child(3)')
            .contains('СВ 556986')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(6) > td:nth-child(4)')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(6) > td:nth-child(5)')
            .contains('3177605615')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(6) > td:nth-child(6)')
            .should('be.visible')
    })
    it('7 lines should have text "Горбань Володимир Володимирович"', () => {
        cy.get('#kontragents > tbody > tr:nth-child(7)')
            .contains('Горбань Володимир Володимирович')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(7) > td:nth-child(2)')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(7) > td:nth-child(3)')
            .contains('СА 729676')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(7) > td:nth-child(4)')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(7) > td:nth-child(5)')
            .contains('2434006558')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(7) > td:nth-child(6)')
            .should('be.visible')
    })
    it('8 lines should have text "Дьомін Микола Леонідович"', () => {
        cy.get('#kontragents > tbody > tr:nth-child(8)')
            .contains('Дьомін Микола Леонідович')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(8) > td:nth-child(2)')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(8) > td:nth-child(3)')
            .contains('АК 677556')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(8) > td:nth-child(4)')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(8) > td:nth-child(5)')
            .contains('2576312355')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(8) > td:nth-child(6)')
            .should('be.visible')
    })
    it('9 lines should have text "Нестерова Ганна Володимирівна"', () => {
        cy.get('#kontragents > tbody > tr:nth-child(9)')
            .contains('Нестерова Ганна Володимирівна')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(9) > td:nth-child(2)')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(9) > td:nth-child(3)')
            .contains('СВ 154975')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(9) > td:nth-child(4)')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(9) > td:nth-child(5)')
            .contains('3065517062')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(9) > td:nth-child(6)')
            .should('be.visible')
    })
    it('10 lines should have text "Дацко Ігор Олександрович"', () => {
        cy.get('#kontragents > tbody > tr:nth-child(10)')
            .contains('Дацко Ігор Олександрович')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(10) > td:nth-child(2)')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(10) > td:nth-child(3)')
            .contains('СВ 824897')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(10) > td:nth-child(4)')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(10) > td:nth-child(5)')
            .contains('3181407998')
            .should('be.visible')
        cy.get('#kontragents > tbody > tr:nth-child(10) > td:nth-child(6)')
            .should('be.visible')
    })
    it('should be declared 10 lines and button', () => {
        cy.get('#kontragents > tbody > tr > td > div').should('be.visible').should('have.length', 10)
        cy.get('#kontragents > tbody > tr > td > div > a.btn.btn-default.btn-xs').should('be.visible').should('have.length', 10)
        cy.get('#kontragents > tbody > tr > td > div > a.btn.btn-xs.btn-warning.select-contragent').should('be.visible').should('have.length', 10)
    })
    it('should be declared 1 button span', () => {
        cy.get('#modal-default > div > div > div.modal-header > button > span').should('be.visible').should('have.length', 1)
    })
    it('should be declared 1 lines and button', () => {
        cy.get('#modal-default > div > div > div.modal-footer').should('be.visible').should('have.length', 1)
        cy.get('#modal-default > div > div > div.modal-footer > button').should('be.visible').should('have.length', 1)
    })
    it('ПІБ/Назва', () => {
        const example = 'Власов'
        cy.get('#modal-default').contains('ПІБ/Назва').should('be.visible')
        cy.intercept('POST', '**/find-customer-by-data',
            cy.spy().as('requestSpy')
        ).as('request')
        cy.get('@requestSpy')
            .should('not.have.been.called')
        cy.get('#kontragents > thead > tr > th:nth-child(1)').type(example)
        cy.wait('@request')
        cy.get('@requestSpy')
        cy.get('#kontragents > tbody > tr').each(row => {
            cy.wrap(row).find('td:nth-child(1)').first().invoke('text').should('match', new RegExp(example, 'i'))
        })
        cy.get('#modal-default').should('be.visible')
            .get('#kontragents > thead > tr > th:nth-child(1)')
            .type('{selectAll}{backspace}')
            cy.wait('@request')
    })
    it('ПІБ/Назва', () => {
        const example = 'ВЛАСОВ'
        cy.get('#modal-default').contains('ПІБ/Назва').should('be.visible')
        cy.intercept('POST', '**/find-customer-by-data',
            cy.spy().as('requestSpy')
        ).as('request')
        cy.get('@requestSpy')
            .should('not.have.been.called')
        cy.get('#kontragents > thead > tr > th:nth-child(1)').type(example)
        cy.wait('@request')
        cy.get('@requestSpy')
            .should('be.calledOnce')
        cy.get('#kontragents > tbody > tr').each(row => {
            cy.wrap(row).find('td:nth-child(1)').first().invoke('text').should('match', new RegExp(example, 'i'))
        })
        cy.get('#modal-default').should('be.visible')
            .get('#kontragents > thead > tr > th:nth-child(1)')
            .type('{selectAll}{backspace}')
            cy.wait('@request')

    })
    it('Номер телефону', () => {
        const example = '099'
        cy.get('#modal-default').contains('Номер телефону').should('be.visible')
        cy.intercept('POST', '**/find-customer-by-data',
            cy.spy().as('requestSpy')
        ).as('request')
        cy.get('@requestSpy')
            .should('not.have.been.called')
        cy.get('#kontragents > thead > tr > th:nth-child(2)').type(example)
        cy.wait('@request')
        cy.get('@requestSpy')
            .should('be.calledOnce')
        cy.get('#kontragents > tbody > tr').each(row => {
            cy.wrap(row).find('td:nth-child(2)').first().invoke('text').should('match', new RegExp(example))
        })
        cy.get('#modal-default').should('be.visible')
            .get('#kontragents > thead > tr > th:nth-child(2)')
            .type('{selectAll}{backspace}')
            cy.wait('@request')
    })
    it('Серія та номер паспорта', () => {
        const example = '435195'
        cy.get('#modal-default').contains('Серія та номер паспорта').should('be.visible')
        cy.intercept('POST', '**/find-customer-by-data',
            cy.spy().as('requestSpy')
        ).as('request')
        cy.get('@requestSpy')
            .should('not.have.been.called')
        cy.get('#kontragents > thead > tr > th:nth-child(3)').type(example)
        cy.wait('@request')
        cy.get('@requestSpy')
            .should('be.calledOnce')
        cy.get('#kontragents > tbody > tr').each(row => {
            cy.wrap(row).find('td:nth-child(3)').first().invoke('text').should('match', new RegExp(example))
        })
        cy.get('#modal-default').should('be.visible')
            .get('#kontragents > thead > tr > th:nth-child(3)')
            .type('{selectAll}{backspace}')
        cy.wait('@request')    
    })
    it('Код', () => {
        const example = '24921'
        cy.get('#modal-default').contains('Код').should('be.visible')
        cy.intercept('POST', '**/find-customer-by-data',
            cy.spy().as('requestSpy')
        ).as('request')
        cy.get('@requestSpy')
            .should('not.have.been.called')
        cy.get('#kontragents > thead > tr > th:nth-child(4)').type(example)
        cy.wait('@request')
        cy.get('@requestSpy')
            .should('be.calledOnce')
        cy.get('#kontragents > tbody > tr').each(row => {
            cy.wrap(row).find('td:nth-child(4)').first().invoke('text').should('match', new RegExp(example))
        })
        cy.get('#kontragents > thead > tr > th:nth-child(4)').type(" ")
        cy.get('#kontragents > thead > tr > th:nth-child(4)').type(" ")
        cy.get('@requestSpy')
            .should('be.calledTwice')
        cy.get('#modal-default').should('be.visible')
            .get('#kontragents > thead > tr > th:nth-child(4)')
            .type('{selectAll}{backspace}')
            cy.wait('@request')
    
    })
    it('ІПН/ЄГРПОУ', () => {
        const example = '9679'
        cy.get('#modal-default').contains('ІПН/ЄГРПОУ').should('be.visible')
        cy.intercept('POST', '**/find-customer-by-data',
            cy.spy().as('requestSpy')
        ).as('request')
        cy.get('@requestSpy')
            .should('not.have.been.called')
        cy.get('#kontragents > thead > tr > th:nth-child(5)').type(example)
        cy.wait('@request')
        cy.get('@requestSpy')
            .should('be.calledOnce')
        cy.get('#kontragents > tbody > tr').each(row => {
            cy.wrap(row).find('td:nth-child(5)').first().invoke('text').should('match', new RegExp(example))
        })
        cy.get('#modal-default').should('be.visible')
            .get('#kontragents > thead > tr > th:nth-child(5)')
            .type('{selectAll}{backspace}')
            cy.wait('@request')
    })
    // it('Вибрати', () => {
    //     cy.get('#modal-default').should('be.visible')
    //         .get('#kontragents > tbody > tr').eq(3).get('#kontragents > tbody > tr:nth-child(4) > td:nth-child(6) > div > a.btn.btn-xs.btn-warning.select-contragent').click()
    //         .wait(3000)
    //         .get('#form > div > div:nth-child(1) > div > div.row > div:nth-child(4) > div > a').click()
        // .get('#kontragents > tbody > tr').eq(3).get('#kontragents > tbody > tr:nth-child(4) > td:nth-child(6) > div > a.btn.btn-default.btn-xs').click()
    // })
    // it('Створити', () => {
    //     cy.get('#kontragents > thead > tr > th:nth-child(6) > a').click()
    //     cy.get('#modal-create-kontragent').should('be.visible')
    //     cy.get('#modal-create-kontragent > div > div > div > div > h4')
    //         .contains('Створити Контрагента')
    //         .should('be.visible')
    // })
})

