describe('Дані про доставку field', () => {
    before(() => {
        cy.visit('/order/create?usa=1')
    })
    it('field should be visisble', () => {
        cy.get('#form')
            .get('#form > div > div:nth-child(2) > h4:nth-child(14)')
            .contains('Дані про доставку')
            .parent()
            .should('be.visible')
    })
    it('field should be visisble div Адресат доставки', () => {
        cy.get('#form')
            .get('#form > div > div:nth-child(2) > div:nth-child(15)').should('be.visible')
            .get('#form > div > div:nth-child(2) > div:nth-child(15) > label')
            .contains('Адресат доставки')
            .parent()
            .should('be.visible')
    })
    it('should be declared 3 div', () => {
        cy.get('#form > div > div:nth-child(2) > div:nth-child(15) > div').should('be.visible').should('have.length', 3)
    })
    it('field should be visisble 3 radio', () => {
        cy.get('[type="radio"]')
            // .check()
            // cy.get('#form > div > div:nth-child(2) > div:nth-child(15) > div > label > input[type=radio]')
            .should('have.length', 3)
    })
    it('should be declared 5 headers div', () => {
        cy.get('#form > div > div:nth-child(2) > div.np-loader_data > div > div').should('be.visible')
            .should('have.length', 5)
    })
    it('1 header div should have text "Тип доставки"', () => {
        cy.get('#form')
            .find('.left_text')
            .contains('Тип доставки')
            .parent()
            .should('be.visible')
            .find('span .select2-selection__arrow')
            .click()
        // .wait(3000).click({ force: true })
        cy.intercept('POST', '**/autocomplete-declarant')
        cy.get('#form > div > div:nth-child(2) > div.np-loader_data > div > div:nth-child(1) > div > span > span.selection > span')
            .type('Новая Почта - адрес')
            .get('[id^=select2-delivery_type]')
            .first().click()
        cy.get('#form')
            .find('.left_text')
            .contains('Тип доставки')
            .parent()
            .should('be.visible')
            .find('span .select2-selection__arrow')
            .click()
        // .wait(3000).click({ force: true })
        cy.intercept('POST', '**/autocomplete-declarant')
        cy.get('ul[id^=select2-delivery_type] > li')
            .eq(5).click()
    })
    it('2 header div should have text "Відділення НП"', () => {
        cy.intercept('POST', '**/autocomplete-delivery-warehouse',
            cy.spy().as('requestSpy')).as('asdasd')
        cy.get('@requestSpy')
            .should('not.have.been.called')
        cy.get('#form')
            .find('.left_text')
            .contains('Відділення НП')
            .parent()
            .should('be.visible')
            .find('span .select2-selection__arrow')
            .click({ force: true })
        // .wait(3000).click({ force: true })
        cy.intercept('POST', '**/autocomplete-declarant')
        cy.get('#form > div > div:nth-child(2) > div.np-loader_data > div > div:nth-child(2) > div > span > span.selection > span')
            .type('Відділення №15 (до 30 кг): вул. Курузова, 5')

        cy.wait('@asdasd')
        cy.wait(1000)
        cy.get('ul[id^=select2-delivery_warehouse] > li')
        cy.get('@requestSpy')
            .should('have.been.calledOnce')

        // .first().click()

    })
    it('3 header div should have text "Населений пункт"', () => {
        cy.intercept('POST', '**/autocomplete-delivery-warehouse',
            cy.spy().as('requestSpy')).as('asdasd')
        cy.get('@requestSpy')
            .should('not.have.been.called')
        cy.get('#form')
            .find('.left_text')
            .contains('Населений пункт')
            .parent()
            .should('be.visible')
            .find('span .select2-selection__arrow')
            .click({ force: true })
            .wait(3000).click({ force: true })
    })
    it('4 header div should have text "ПІБ отримувача"', () => {
        cy.get('#form')
            .find('.left_text')
            .contains('ПІБ отримувача')
            .parent()
            .should('be.visible')
    })
    it('5 header div should have text "Телефон отримувача"', () => {
        cy.get('#form')
            .find('.left_text')
            .contains('Телефон отримувача')
            .parent()
            .should('be.visible')
    })
    it('field should be visisble Клиент div', () => {
        cy.get('#form')
            .get('#form > div > div:nth-child(2) > div:nth-child(15) > div:nth-child(2)').should('be.visible')
            .get('#form > div > div:nth-child(2) > div:nth-child(15) > div:nth-child(2) > label').should('be.visible')
            .contains('Клиент').should('be.visible')
    })
    it('field should be visisble  radio Клиент', () => {
        cy.get('#form > div > div:nth-child(2) > div:nth-child(15) > div:nth-child(2) > label > input[type=radio]')
            .should('be.visible').click()
    })
    it('asd', () => {
        cy.get('#form > div > div:nth-child(2) > div.np-loader_data > div > div').as('inputs')
        cy.get('@inputs').eq(0).contains('Тип доставки')
        cy.get('@inputs').eq(1).contains('Населений пункт')
        cy.get('@inputs').eq(2).contains('Відділення НП')
        cy.get('@inputs').eq(3).contains('ПІБ отримувача')
        cy.get('@inputs').eq(4).contains('Населений пункт')
        cy.get('@inputs').eq(5).contains('Телефон отримувача')
        cy.wait(1000)
        cy.get('@inputs').eq(0).contains('Тип доставки')
        cy.get('@inputs').eq(1).contains('Населений пункт')
        cy.get('@inputs').eq(2).contains('Відділення НП')
        cy.get('@inputs').eq(3).contains('ПІБ отримувача')
        cy.get('@inputs').eq(4).contains('Населений пункт')
        cy.get('@inputs').eq(5).contains('Телефон отримувача')
    })
    it('field should be visisble  radio Лаборатория', () => {
        cy.get('#form > div > div:nth-child(2) > div:nth-child(15) > div:nth-child(3) > label > input[type=radio]')
            .should('be.visible').click().wait(3000)
    })
    it('field should be visisble  radio Самовывоз', () => {
        cy.get('#form > div > div:nth-child(2) > div:nth-child(15) > div:nth-child(4) > label > input[type=radio]')
            .should('be.visible').click()
    })
    it('field should be visisble Статус and checkbox', () => {
        cy.get('#form > div > div:nth-child(1) > div > div:nth-child(2)').should('be.visible')
    })
    it('field should be visisble Статус', () => {
        cy.get('#form')
            .contains('Статус')
            .parent()
            .should('be.visible')
    })
    it('field should be visisble 4 div', () => {
        cy.get('#form > div > div:nth-child(1) > div > div:nth-child(2) > div > div')
            .should('have.length', 4)
    })
    it('field should be visisble 4 checkbox', () => {
        cy.get('#form > div > div:nth-child(1) > div > div:nth-child(2)')
            .find('[type="checkbox"]')
            // cy.get('#form > div > div:nth-child(1) > div > div:nth-child(2) > div > div > label > input[type=checkbox]')
            // .check()
            .should('have.length', 4)
    })
    it('disabled checkbox', () => {
        cy.get(':checkbox').not('[disabled]').click({ multiple: true })
        cy.get(':checkbox:disabled')
        cy.get(':checkbox').each((checkbox, index) => {
            if (index === 1 || index === 2 || index === 4) {
                cy.wrap(checkbox).should('have.attr', 'disabled')
            } else {
                cy.wrap(checkbox).should('have.not.attr', 'disabled')
            }
        })
    })
    it('button should. be. visible', () => {
        cy.get('#form > div > div.form-group.fixed_buttons.col-md-12.col-sm-12 > button').contains('Провести та закрити')
            .should('be.visible')
    })
    it.only('4 button', () => {
        cy.get('#form > div > div.form-group.fixed_buttons.col-md-12.col-sm-12 > button')
            .should('have.length', 4)
            .should('not.be.disabled')
    })
})