describe('Марка виробника', () => {
    before(() => {
        cy.visit('/order/create?usa=1')
    })
    it('field should be visisble', () => {
        cy.get('#form')
            .find('.left_text')
            .contains('Марка виробника')
            .parent()
            .should('be.visible')
            .find('span .select2-selection__arrow')
            .click()
        cy.intercept('POST', '**/autocomplete-declarant')
        cy.get('#form > div > div:nth-child(1) > div > div.row > div:nth-child(10) > div').type('AUDI')
        cy.get('[id^=select2-manufacturer_brand_id-] > li').first().click()
        cy.get('#form')
            .find('.left_text')
            .contains('Торгові найменування')
            .parent()
            .should('be.visible')
            .find('span .select2-selection__arrow')
            .click()
        cy.intercept('POST', '**/autocomplete-declarant')
        cy.get('#form > div > div:nth-child(1) > div > div.row > div:nth-child(11) > div').type('Q5')
        cy.get('[id^=select2-trade_item_id-] > li').first().click()
    })
})